### ISSUE TITLE
License and permission to use in AVS port

### ISSUE THREAD

**Issue by grandchild** [TomyLobo/eeltrans#1]
Hi there,

I'd like to know if you'd consider using a BSD license for this (same as the AVS source code).

Secondly, I'm working on an AVS port to GCC [here](/grandchild/vis_avs), and it's looking nice so far. AVS Trans is a key component. I've decided to bundle all the most important APEs into AVS itself, so would you be okay, with me adding a version of this code to the repo there?

Thanks for sharing the code, and thanks in advance!

PS: Did you also write Triangle APE? I'm dreading rewriting that from scratch...

**Comment by grandchild** [comment]
(I did a similar thing with Convolution Filter and TexerII, if you want examples. I'm currently [finishing up TexerII](/grandchild/vis_avs/commits/wip/texer2).)

**Comment by TomyLobo** [comment]
Sorry, i totally missed this issue until now.
Sure you can have it. What do you need to me to do?
You probably want to use avstrans only, not any part of the APE, cause the only purpose of that is injecting the transpiler into eel, but you can just straight up change eel to incorporate avstrans.
The APE is also full of intel-style ASM which you'd probably have to translate. another reason to avoid it :)

Yes, I also wrote triangle APE. But it's probably better to grab some other triangle renderer though. It's so much ASM that it's not funny anymore. 99% could be C++.

Btw, you have my permission to dig up my email address from git history to mail me.
I'm also on [Steam](https://steamcommunity.com/id/tomylobo/) and Discord (TomyLobo#6785)

**Comment by TomyLobo** [comment]
Good news, I found my old AVS projects directory, including the source for triangle.ape (under "Kopie von APEtriangle") as well as my attempt to use a hardware renderer for the triangles (under "APEtriangle").
Contact me via email/Steam/Discord if you want it.

**Comment by TomyLobo** [comment]
https://www.deviantart.com/piarlavs/art/PiARLAVS-07-The-Final-Pack-892667165 I just found this person in my deviantart followers. They released a pack 3 days ago. Is AVS really still alive after all these years?

**Comment by grandchild** [comment]
Oh, I'm so happy you wrote! Will hit you up on discord 😃 
I already started rewriting Triangle, but I'm happy to ditch Ghidra for the real source.

I use Intel syntax anyway, since GCC supports it, didn't want to be bothered with AT&T, heh 😋

And thanks for the dA link, I hardly every check there since the categories are mostly gone :/ But yeah, there's isolated pockets of AVS activity from time to time.
